In [4]:
## 혼동 행렬 구현

import numpy as np
from sklearn.metrics import confusion_matrix

# 0이 양성, 1이 음성
y_true = [0, 0, 0, 1, 1, 1]
y_pred = [1, 0, 0, 1, 1, 1]

confmat = confusion_matrix(y_true, y_pred)

print(confmat)

[[2 1]
 [0 3]]


In [8]:
## 성능평가지표 구현
# 적합률, 재현율, F
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score, f1_score

y_true = [1, 1, 1, 0, 0, 0]
y_pred = [0, 1, 1, 0, 0, 0]

print(f'Precision: {precision_score(y_true, y_pred):.3f}')
print(f'Recall: {recall_score(y_true, y_pred):.3f}')
print(f'F1: {f1_score(y_true, y_pred):.3f}')

Precision: 1.000
Recall: 0.667
F1: 0.800


In [9]:
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1_score = 2 * (precision * recall) / (precision + recall)

In [10]:
f1_score

0.8

In [12]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = datasets.load_iris()
X = iris.data[:, [2, 3]]
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)

svc = svm.SVC(C=1, kernel='rbf', gamma=0.01)
svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred):.2f}%')

Accuracy: 0.98%


In [17]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [15]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])