#### 7. NumPy

In [18]:
import numpy as np
import time
from numpy.random import rand

N = 150

matA = np.array(rand(N, N))
matB = np.array(rand(N, N))

matC = np.array([[0] * N for _ in range(N)])

start = time.time()

for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print(f'파이썬 기능만으로 계산한 결과: {time.time() - start:.2f}sec')

start = time.time()

matC = np.dot(matA, matB)
print(f'NumPy를 사용하여 계산한 결과: {time.time() - start:.2f}sec')

파이썬 기능만으로 계산한 결과: 1.88sec
NumPy를 사용하여 계산한 결과: 0.00sec


In [20]:
storages = [24, 3, 4, 23, 10, 12]
np_storages = np.array(storages)
type(np_storages)

numpy.ndarray

In [22]:
arr = np.array([2, 5, 3, 4, 8])
print(arr ** 3)
print(1 / arr)

[  8 125  27  64 512]
[0.5        0.2        0.33333333 0.25       0.125     ]


In [30]:
arr = list(range(1, 11))
print(arr)
arr[0:3] = 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


TypeError: can only assign an iterable

In [32]:
arr = np.arange(10)
print(arr)
arr[0:3] = 1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 3 4 5 6 7 8 9]


In [40]:
# 파이썬 리스트와 다르게 copy를 해야함
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

print(arr1)

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


In [38]:
## 부울 인덱스
arr = np.array([2, 4, 6, 7])
print(arr[np.array([True, True, True, False])])

[2 4 6]


In [35]:
print(arr[arr % 3 == 1])

[4 7]


In [37]:
print(arr % 2 == 0)
print(arr[arr % 2 == 0])

[ True  True  True False]
[2 4 6]


In [42]:
## 범용 함수(universal function) - ndarray 배열의 각 요소에 대한 연산 결과를 반환
arr = np.array([4, -9, 16, -4, 20])
print(arr)
arr_abs = np.abs(arr)
print(arr_abs)
print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [43]:
## 집합 함수 - 1차원 배열만을 취급
arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

print(np.unique(arr1))
print(np.union1d(arr1, arr2))
print(np.intersect1d(arr1, arr2))
print(np.setdiff1d(arr1, arr2))

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


In [45]:
## 난수
from numpy.random import randint

arr1 = randint(0, 11, (5, 2))
print(arr1)

arr2 = np.random.rand(3)
print(arr2)

[[8 1]
 [5 6]
 [1 9]
 [9 6]
 [9 6]]
[0.27484865 0.83021785 0.66465335]


In [46]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)
print(arr.reshape(4, 2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
arr[1]

array([5, 6, 7, 8])

In [48]:
arr[1][2]

7

In [49]:
arr[1,2]

7

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[0, 2]

3

In [53]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [57]:
arr = np.arange(25).reshape(5, 5)
print(arr[[1, 3, 0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [60]:
arr = np.arange(10).reshape(2, 5)
print(arr)
arr.T

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [63]:
arr = np.array([15, 30, 5])
arr.argsort() # index의 위치를 return

array([2, 0, 1], dtype=int64)

In [66]:
np.sort(arr)

array([ 5, 15, 30])

In [70]:
arr = np.array([[8, 4, 2], [3, 5, 1]])
arr.sort(1)
print(arr)
arr.sort(0)
print(arr)

[[2 4 8]
 [1 3 5]]
[[1 3 5]
 [2 4 8]]


In [72]:
arr = np.arange(9).reshape(3, 3)
print(np.dot(arr, arr))

vec = arr.reshape(9)
print(np.linalg.norm(vec))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
14.2828568570857


In [77]:
## 통계 함수
arr = np.arange(15).reshape(3, 5)
print(arr)
print(arr.mean(axis=0))
print(arr.sum(axis=1))
print(arr.min())
print(arr.argmax(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


In [79]:
## 브로드캐스트 - 크기가 작은 배열의 열 또는 행을 큰 배열 쪽으로 자동으로 맞춤
x = np.arange(6).reshape(2, 3)
print(x + 1)

[[1 2 3]
 [4 5 6]]
