In [1]:
# Numpy의 고속 처리
import numpy as np
import time
from numpy.random import rand

N = 150

matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

start = time.time()

for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print(f"Python For Loop: {time.time() - start:2f}")

start = time.time()
matC = np.dot(matA, matB)

print(f"Numpy: {time.time() - start:2f}")


Python For Loop: 2.096261
Numpy: 0.001997


In [7]:
# Python Deepcopy, Shallow copy
# https://blockdmask.tistory.com/576


In [41]:
# 범용함수(universal function)
# ndarray 배열의 각 요소에 대한 연산 결과를 반환
arr = np.array([4, -9, 16, -4, 20])
print(np.abs(arr))
print(np.exp(arr))
print(np.sqrt(np.abs(arr)))


[ 4  9 16  4 20]
[5.45981500e+01 1.23409804e-04 8.88611052e+06 1.83156389e-02
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [42]:
# 집합 함수
arr1 = [3, 6, 9, 12, 15]
arr2 = [4, 8, 12, 16, 20]
print(np.union1d(arr1, arr2))
print(np.intersect1d(arr1, arr2))
print(np.setdiff1d(arr1, arr2))


[ 3  4  6  8  9 12 15 16 20]
[12]
[ 3  6  9 15]


In [43]:
# 난수
from numpy.random import randint

arr1 = randint(0, 11, (5, 2))
print(arr1)

arr2 = np.random.rand(3)
print(arr2)


[[ 9  5]
 [10  2]
 [ 4  1]
 [ 5 10]
 [10  3]]
[0.14562759 0.96047399 0.36038489]


In [66]:
arr = np.sort(np.random.randn(10))
print(np.mean(arr), np.std(arr))


0.14304058242824538 0.622538422141982


In [68]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)
print(arr.reshape(4, 2))


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [74]:
# 인덱스 참조
# ndarray는 다차원일 경우 ,를 사용하여 접근할 수 있다
lst = [[1, 2, 3, 4],
       [5, 6, 7, 8]]
arr = np.array(lst)
print(arr[1, 2])
print(arr[1, 1:])


7
[6 7 8]


In [77]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
arr[1, 0, 0]

5

In [80]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [85]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(arr.shape)

[5 7 9]
[ 6 15]
(2, 3)


In [90]:
## 팬시 인덱스 참조
# 인덱스의 배열을 이용하여 인덱스를 찾모하는 방법
# 특정 순서로 행을 추출하기 위해서 그 순서를 나타내는 배열을 인덱스 참조로 전달한다

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr[[3, 2, 0]])
print(arr[True])

[[7 8]
 [5 6]
 [1 2]]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [96]:
arr = np.arange(10).reshape(2, 5)
print(arr)
print(arr.T)  # np.transpose(T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [99]:
## 정렬
# argsort를 이용하면 정렬한 배열의 인덱스를 반환

arr = np.array([15, 30, 5])
arr.argsort()

array([2, 0, 1], dtype=int64)

In [100]:
print(arr[arr.argsort()])

[ 5 15 30]


In [105]:
np.sort(arr)  # 정렬한 배열을 반환

array([ 5, 15, 30])

In [108]:
print(arr.sort())  # 배열을 정렬하고 None을 반환(반환값 x)

None


In [112]:
# 특정 축에 대해서만 정렬을 수행할 수 있음
arr = np.array([[8, 4, 2], [3, 5, 1]])
print(arr)
print(np.sort(arr, axis=0))
print(np.sort(arr, axis=1))

[[8 4 2]
 [3 5 1]]
[[3 4 1]
 [8 5 2]]
[[2 4 8]
 [1 3 5]]


In [118]:
## 행렬 계산
arr = np.arange(9).reshape(3, 3)

print(np.dot(arr, arr))

arr1 = np.arange(1, 5).reshape(2, 2)
print(np.dot(arr1, arr1))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 7 10]
 [15 22]]


In [126]:
arr = np.array([[1, 2], [3, 4]])
print(np.linalg.norm(arr))
print(np.sqrt(5 + 25))

5.477225575051661
5.477225575051661
