In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [4]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [7]:
df.iloc[:, 3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [17]:
df.iloc[1:3, :]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [18]:
df[df.age > 30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [19]:
df[(df.age < 35) & (df.decision == True)]

id   name  age  decision
0  1  Fares   32      True

In [22]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22 ,23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [23]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [16]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])