In [2]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

__Numpy Basic__

In [3]:
import numpy as np
np.__version__

'1.24.1'

In [4]:
data = [5, 9, 2.5, 3, 1]
array = np.array(data)
array

array([5. , 9. , 2.5, 3. , 1. ])

In [5]:
data = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
array = np.array(data)
array

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [6]:
array.ndim, array.shape, array.dtype

(2, (2, 5), dtype('int32'))

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((2, 3, 8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [9]:
np.arange(5, 30, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [10]:
array = np.array([1, 2, 3, 4, 5, 7, 8, 9, 10])
array.cumsum(), array.cumprod()

(array([ 1,  3,  6, 10, 15, 22, 30, 39, 49]),
 array([     1,      2,      6,     24,    120,    840,   6720,  60480,
        604800]))

In [11]:
np.percentile(array, 0), np.percentile(array, 25), np.percentile(array, 50), np.percentile(array, 75)

(1.0, 3.0, 5.0, 8.0)

In [12]:
array = np.random.randn(50)
(array > 0).sum()

20

__Pandas Basic__

In [13]:
import pandas as pd
pd.__version__

'1.4.4'

In [14]:
ser = pd.Series([1, 3, 5, 7, 9])
ser

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [15]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
ser.values

array([1, 3, 5, 7, 9], dtype=int64)

In [17]:
data = np.random.randint(0, 10, 5)
index = ["a", "b", "c", "d", "e"]
series = pd.Series(data=data, index=index, name="series_from_ndarray")
series

a    8
b    1
c    1
d    3
e    0
Name: series_from_ndarray, dtype: int32

In [18]:
data = {"서울": 70000, "부산": 52000, "대전": 35000, "광주": 40000, "제주도": 28000}
series = pd.Series(data=data)
series

서울     70000
부산     52000
대전     35000
광주     40000
제주도    28000
dtype: int64

In [19]:
city = ["광주", "대전", "부산", "서울", "울릉도"]
series = pd.Series(data=data, index=city, name="series_from_dict")
series

광주     40000.0
대전     35000.0
부산     52000.0
서울     70000.0
울릉도        NaN
Name: series_from_dict, dtype: float64

In [20]:
series.name

'series_from_dict'

In [21]:
series.values

array([40000., 35000., 52000., 70000.,    nan])

In [22]:
series_tolist = series.tolist()
series_tolist, type(series_tolist)

([40000.0, 35000.0, 52000.0, 70000.0, nan], list)

In [23]:
data = {'도시' : ['서울', '서울', '서울', '부산', '부산', '부산'],
        '연도' : [2020, 2019, 2018, 2020, 2019, 2018],
        '인구수' : [15865, 15964, 16034, 4342, 4380, 4416]}

frame = pd.DataFrame(data)
frame

도시    연도    인구수
0  서울  2020  15865
1  서울  2019  15964
2  서울  2018  16034
3  부산  2020   4342
4  부산  2019   4380
5  부산  2018   4416

In [25]:
frame = pd.DataFrame(data, columns=["연도", "도시", "인구수"])
frame

연도  도시    인구수
0  2020  서울  15865
1  2019  서울  15964
2  2018  서울  16034
3  2020  부산   4342
4  2019  부산   4380
5  2018  부산   4416

In [27]:
frame = pd.DataFrame(data, columns=["연도", "도시", "인구수", "변화율"])
frame

연도  도시    인구수  변화율
0  2020  서울  15865  NaN
1  2019  서울  15964  NaN
2  2018  서울  16034  NaN
3  2020  부산   4342  NaN
4  2019  부산   4380  NaN
5  2018  부산   4416  NaN

In [28]:
data = {'컬럼1' : pd.Series(data=np.random.randint(10, 100, 5),
                                  index=['가', '나', '다', '라', '마']),
        '컬럼2' : pd.Series(data=np.random.randint(10, 100, 5),
                                  index=['가', '나', '다', '라', '마']),
        '컬럼3' : pd.Series(data=np.random.randint(10, 100, 5),
                                  index=['가', '나', '다', '라', '마'])}

frame = pd.DataFrame(data)
frame

컬럼1  컬럼2  컬럼3
가   43   84   31
나   33   50   97
다   34   61   28
라   63   91   25
마   39   60   73

In [29]:
frame.values

array([[43, 84, 31],
       [33, 50, 97],
       [34, 61, 28],
       [63, 91, 25],
       [39, 60, 73]])

In [33]:
df = pd.read_csv("datasets/example_1.csv")

In [34]:
df

a   b   c   d   e    keyword
0   1   2   3   4   5      Hello
1  11  12  13  14  15       Good
2  21  22  23  24  25       Nice
3  31  32  33  34  35  Beautiful
4  41  42  43  44  45       GoGo

In [37]:
pd.read_table("datasets/example_1.csv", sep=",")

a   b   c   d   e    keyword
0   1   2   3   4   5      Hello
1  11  12  13  14  15       Good
2  21  22  23  24  25       Nice
3  31  32  33  34  35  Beautiful
4  41  42  43  44  45       GoGo

In [39]:
# 원본 데이터에 헤더가 없을 경우 1행을 헤더로 만들지 않도록 요청
pd.read_csv("datasets/example_2.csv", header=None)

0   1   2   3   4          5
0   1   2   3   4   5      Hello
1  11  12  13  14  15       Good
2  21  22  23  24  25       Nice
3  31  32  33  34  35  Beautiful
4  41  42  43  44  45       GoGo

In [40]:
# 일부 행 건너뛰고 데이터 로드
pd.read_csv("datasets/example_1.csv", skiprows=[1, 3])

a   b   c   d   e    keyword
0  11  12  13  14  15       Good
1  31  32  33  34  35  Beautiful
2  41  42  43  44  45       GoGo

In [41]:
pd.read_csv("datasets/example_1.csv", skiprows=lambda x: x > 0 and np.random.rand() > 0.5)

a   b   c   d   e keyword
0  11  12  13  14  15    Good
1  41  42  43  44  45    GoGo